 # Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

gmail_username: info@replenishmd.com
gmail_password: qsmlmxdiewwidgpf
twillio_account_sid: AC34f653b329a03e27979dd8685408aa6a
twillio_auth_token: 8f05bc29270d971bd10dfac0e59d062f
twillio_phone_number: +18446024147
stripe_api_key: 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
stripe_publishable_key: pk_live_51LB9bEBZZntSWQ9m8OiXWCOxMcabAM2O3BfsNbXxYqeFVSOWMrf87AUDnfHk0Fm40MllAuR6feavPheYVKaGVt6N00gEn5IIEg
STRIPE_WEBHOOK_SECRET: whsec_ba54664b1dc3544719214fb2d55c9779be5de6aba212a367f4eafe43d3749d67